services:
  - type: web
    name: awan-server
    env: node
    rootDir: server
    buildCommand: "npm install"
    startCommand: "node server.js"
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
